config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  provider   :string           not null
#  uid        :string           not null
#  name       :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  def self.from_omniauth(auth_hash)
    user = find_or_create_by(
      uid: auth_hash['uid'],
      provider: auth_hash['provider']
    )
    user.name = auth_hash['info']['name']
    user.image_url = auth_hash['info']['image']
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate"
    end
    redirect_to root_url
  end

  def new
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'Logged out!'
    end
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coordinatr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% flash.each do |key, msg| %>
    <ul>
      <li class="<% key %>"><%= msg %></li>
    </ul>
  <% end %>
  <% if logged_in? %>
    <ul>
      <li>Name: <%= current_user.name %></li>
      <li>Provider: <%= current_user.provider %></li>
      <li>Picture: <img src=<%= current_user.image_url %> alt="profile"/></li>
      <li><%= link_to 'Log Out', logout_url, method: :delete %></li>
    </ul>
  <% end %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<% if logged_in? %>
  <div>Hello, <%= current_user.name %>! </div>
<% else %>
  <ul>
    <li><%= link_to 'Log in With Google+', '/auth/google_oauth2' %></li>
    <li><%= link_to 'Log in With Facebook', '/auth/facebook' %></li>
  </ul>
<% end %>